change step

diff --git a/.github/workflows/oasdif.yaml b/.github/workflows/oasdif.yaml
--- a/.github/workflows/oasdif.yaml
+++ b/.github/workflows/oasdif.yaml
@@ -18,7 +18,11 @@ jobs:
         id: oasdiff
         run: |
           docker run --rm -t -v /tmp:/tmp tufin/oasdiff breaking -o ERR /tmp/old_spec.json /tmp/new_spec.json
-          $echo "has_errors=$(if [ $? -ne 0 ]; then echo true; else echo false; fi)" >> $GITHUB_STATE
+          if [ $? -ne 0 ]; then
+            echo "has_errors=true" >> $GITHUB_STATE
+          else
+            echo "has_errors=false" >> $GITHUB_STATE
+          fi
         continue-on-error: true
 
       - name: "Send Slack message on failure"
