update github action

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -25,11 +25,11 @@ jobs:
         id: oasdiff
         run: |
           docker run --rm -t -v /tmp:/tmp tufin/oasdiff breaking -o ERR /tmp/current_spec.json /tmp/new_spec.json
-          echo "::set-output name=has_errors::$(if [ $? -ne 0 ]; then echo true; else echo false; fi)"
+          echo "has_errors=$(if [ $? -ne 0 ]; then echo true; else echo false; fi)" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: "Send Slack message on failure"
-        if: steps.oasdiff.outputs.has_errors == 'true'
+        if: env.has_errors == 'true'
         uses: rtCamp/action-slack-notify@v2
         with:
           status: failure
